import { useEffect, useState } from "react";
import { Link } from "react-router";
import Container from "../../components/shared/Container";
import { EmptyState, ErrorState, LoadingState } from "../../components/shared/FeedbackState";
import PageHeader from "../../components/shared/PageHeader";
import * as courseService from "../../services/course.service";
import type { Course } from "../../types/course.types";
import { getApiErrorMessage } from "../../utils/getApiErrorMessage";

const ManageCourses = () => {
  const [courses, setCourses] = useState<Course[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [deletingId, setDeletingId] = useState("");
  useEffect(() => { let active = true; courseService.getMyCourses().then((response) => { if (active) setCourses(response.data.courses); }).catch((requestError: unknown) => { if (active) setError(getApiErrorMessage(requestError, "Unable to load your courses.")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const remove = async (id: string) => { if (!window.confirm("Delete this course permanently? This action cannot be undone.")) return; setError(""); setDeletingId(id); try { await courseService.deleteCourse(id); setCourses((items) => items.filter((item) => item._id !== id)); } catch (requestError) { setError(getApiErrorMessage(requestError, "Unable to delete course.")); } finally { setDeletingId(""); } };
  const action = <Link to="/add-course" className="btn btn-primary">Add Course</Link>;
  return <main className="py-10 sm:py-12 lg:py-16"><Container><PageHeader eyebrow="Course creator" title="Manage your courses" description="Review, update, or remove the courses published by your account." action={action} />
    {error && <div className="mt-8"><ErrorState title="Something went wrong" description={error} compact /></div>}
    {loading ? <LoadingState label="Loading your courses…" /> : courses.length === 0 ? <div className="mt-8"><EmptyState title="No courses yet" description="Publish your first course to see it here." action={action} /></div> : <>
      <div className="mt-8 grid gap-4 md:hidden">{courses.map((course) => <article key={course._id} className="overflow-hidden rounded-2xl border border-base-300 bg-base-100 shadow-sm"><div className="flex gap-4 p-4"><img src={course.image} alt="" className="size-20 shrink-0 rounded-xl object-cover" /><div className="min-w-0"><h2 className="line-clamp-2 font-semibold">{course.title}</h2><p className="mt-1 text-sm text-base-content/60">{course.category} · ৳{course.price.toLocaleString()}</p><p className="mt-1 text-xs text-base-content/50">★ {course.rating || "New"} · {new Date(course.createdAt).toLocaleDateString()}</p></div></div><div className="grid grid-cols-3 gap-2 border-t border-base-300 p-3"><Link to={`/courses/${course._id}`} className="btn btn-ghost btn-sm">View</Link><Link to={`/courses/${course._id}/edit`} className="btn btn-outline btn-sm">Edit</Link><button type="button" onClick={() => void remove(course._id)} disabled={deletingId === course._id} className="btn btn-outline btn-error btn-sm">{deletingId === course._id ? <span className="loading loading-spinner loading-xs" /> : "Delete"}</button></div></article>)}</div>
      <div className="mt-8 hidden overflow-hidden rounded-2xl border border-base-300 bg-base-100 shadow-sm md:block"><div className="overflow-x-auto"><table className="table"><thead className="bg-base-200"><tr><th>Course</th><th>Category</th><th>Price</th><th>Rating</th><th>Date</th><th className="text-right">Actions</th></tr></thead><tbody>{courses.map((course) => <tr key={course._id}><td><div className="flex items-center gap-3"><img src={course.image} alt="" className="size-12 rounded-lg object-cover" /><span className="max-w-56 line-clamp-2 font-semibold">{course.title}</span></div></td><td>{course.category}</td><td>৳{course.price.toLocaleString()}</td><td>★ {course.rating || "New"}</td><td>{new Date(course.createdAt).toLocaleDateString()}</td><td><div className="flex justify-end gap-2"><Link to={`/courses/${course._id}`} className="btn btn-ghost btn-sm">View</Link><Link to={`/courses/${course._id}/edit`} className="btn btn-outline btn-sm">Edit</Link><button type="button" onClick={() => void remove(course._id)} disabled={deletingId === course._id} className="btn btn-outline btn-error btn-sm">{deletingId === course._id ? <span className="loading loading-spinner loading-xs" /> : "Delete"}</button></div></td></tr>)}</tbody></table></div></div></>}
  </Container></main>;
};
export default ManageCourses;
