import { useState, type FormEvent } from "react";
import type { Course, CourseLevel, CreateCoursePayload } from "../../types/course.types";

interface Props { course?: Course; submitLabel: string; submitting: boolean; error: string; onSubmit: (payload: CreateCoursePayload) => Promise<void>; }
const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
const CourseForm = ({ course, submitLabel, submitting, error, onSubmit }: Props) => {
  const [values, setValues] = useState({ title: course?.title ?? "", shortDescription: course?.shortDescription ?? "", fullDescription: course?.fullDescription ?? "", category: course?.category ?? "", level: course?.level ?? "Beginner" as CourseLevel, price: String(course?.price ?? ""), duration: course?.duration ?? "", image: course?.image ?? "", additionalImages: course?.additionalImages.join("\n") ?? "", learningOutcomes: course?.learningOutcomes.join("\n") ?? "", requirements: course?.requirements.join("\n") ?? "" });
  const set = (name: keyof typeof values, value: string) => setValues((current) => ({ ...current, [name]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); const price = Number(values.price); if (price < 0) return; void onSubmit({ ...values, level: values.level as CourseLevel, price, additionalImages: lines(values.additionalImages), learningOutcomes: lines(values.learningOutcomes), requirements: lines(values.requirements) }); };
  return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-primary/10 bg-base-100 p-6 shadow-sm md:p-8">{error && <div className="alert alert-error"><span>{error}</span></div>}
    <label className="block"><span className="label-text font-semibold">Course title</span><input value={values.title} onChange={(e) => set("title", e.target.value)} className="input input-bordered mt-2 w-full" required minLength={5} /></label>
    <label className="block"><span className="label-text font-semibold">Short description</span><textarea value={values.shortDescription} onChange={(e) => set("shortDescription", e.target.value)} className="textarea textarea-bordered mt-2 min-h-24 w-full" required minLength={20} /></label>
    <label className="block"><span className="label-text font-semibold">Full description</span><textarea value={values.fullDescription} onChange={(e) => set("fullDescription", e.target.value)} className="textarea textarea-bordered mt-2 min-h-40 w-full" required minLength={50} /></label>
    <div className="grid gap-5 sm:grid-cols-2"><label><span className="label-text font-semibold">Category</span><input value={values.category} onChange={(e) => set("category", e.target.value)} className="input input-bordered mt-2 w-full" required /></label><label><span className="label-text font-semibold">Level</span><select value={values.level} onChange={(e) => set("level", e.target.value)} className="select select-bordered mt-2 w-full">{["Beginner","Intermediate","Advanced"].map((level) => <option key={level}>{level}</option>)}</select></label></div>
    <div className="grid gap-5 sm:grid-cols-2"><label><span className="label-text font-semibold">Price</span><input type="number" min="0" value={values.price} onChange={(e) => set("price", e.target.value)} className="input input-bordered mt-2 w-full" required /></label><label><span className="label-text font-semibold">Duration</span><input value={values.duration} onChange={(e) => set("duration", e.target.value)} className="input input-bordered mt-2 w-full" required /></label></div>
    <label className="block"><span className="label-text font-semibold">Image URL</span><input type="url" value={values.image} onChange={(e) => set("image", e.target.value)} className="input input-bordered mt-2 w-full" required /></label>
    {[{key:"additionalImages", label:"Additional image URLs"},{key:"learningOutcomes", label:"Learning outcomes"},{key:"requirements", label:"Requirements"}].map(({key,label}) => <label key={key} className="block"><span className="label-text font-semibold">{label}</span><textarea value={values[key as keyof typeof values]} onChange={(e) => set(key as keyof typeof values, e.target.value)} className="textarea textarea-bordered mt-2 min-h-28 w-full" placeholder="One value per line" /></label>)}
    <button type="submit" disabled={submitting} className="btn btn-primary w-full">{submitting && <span className="loading loading-spinner" />}{submitLabel}</button>
  </form>;
};
export default CourseForm;
